/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"


int main () {
    std::cout << "Speqtral starting.." << std::endl;
    return 0;
}
